### ISSUE TITLE
Membership_data[i].at(j) not working for output to text file

### ISSUE THREAD

**Issue by KriziaHB** [KriziaHB/Wine-DMProject#19]
![image](https://cloud.githubusercontent.com/assets/15699916/24458788/8c4e823c-145f-11e7-825b-37eb3bba7244.png)

**Comment by KriziaHB** [comment]
See watch number 4 showing that j is undefined when j above is showing a value

**Comment by KriziaHB** [comment]
![image](https://cloud.githubusercontent.com/assets/15699916/24459466/3f8dd4fa-1461-11e7-8d8d-ca9e583df5aa.png)

**Comment by christmoore** [comment]
Please use [this link](http://stackoverflow.com/questions/6406356/writing-vector-values-to-a-file) for copying the vector to a text file.

**Comment by KriziaHB** [comment]
Thanks! I will look at it after class

**Comment by KriziaHB** [comment]
![image](https://cloud.githubusercontent.com/assets/15699916/24471416/ae2c11f8-1487-11e7-8832-8f41337caa09.png)
Latest version: 
-needs to have mod value included in the filename 
-still not writing from membership_data vector

**Comment by christmoore** [comment]
Fixed
